export enum Exams {
  GS1 = "GS1",
  GS2 = "GS2",
  GS3 = "GS3",
  GS4 = "GS4",
}

export enum Marks {
  TEN = "10",
  FIFTEEN = "15",
  TWENTY = "20",
}

export enum Words {
  ONE_FIFTY = "150",
  TWO_FIFTY = "250",
  THREE_HUNDERED = "300",
}

export enum Subjects {
  // General studies one
  HISTORY = "HISTORY",
  GEOGRAPHY = "GEOGRAPHY",
  INDIAN_SOCIETY = "INDIAN_SOCIETY",

  // GS 2
  POLITY_CONSTITUTION_AND_GOVERNANCE = "POLITY_CONSTITUTION_AND_GOVERNANCE",
  SOCIAL_JUSTICE = "SOCIAL_JUSTICE",
  INTERNATIONAL_RELATIONS = "INTERNATIONAL_RELATIONS",

  // GS 3
  ECONOMY = "ECONOMY",
  SCIENCE_AND_TECHNOLOGY = "SCIENCE_AND_TECHNOLOGY",
  ENVIRONMENT_DISASTER_AND_MANAGEMENT = "ENVIRONMENT_DISASTER_AND_MANAGEMENT",
  INTERNAL_SECURITY = "INTERNAL_SECURITY",
  AGRICULTURE = "AGRICULTURE",

  // GS 4
  ETHICS_INTEGRITY_AND_APTITUDE = "ETHICS_INTEGRITY_AND_APTITUDE",
}
